### PR TITLE
Add simple way to handle users mentions by notionUid

### PR DESCRIPTION
**Pull request by mahmuodmasri**

### CODE REVIEW

**Comment by mayneyao** [comment]
Thanks for your work, I will check it later.

**Comment by mahmuodmasri** [comment]
I also improved the support for dates

**Comment by mayneyao** [comment]
good job

**Comment by mahmuodmasri** [comment]
Oh, It wasn't ready to be merged yet!, I should have marked it as draft, anyway I created another pull request #4 to complete this one, this time it's ready to be merged.

**Pull request merged**
